spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:nisum
    driver-class-name: org.h2.Driver
    username: gustavo
    password: 1234

swagger:
  title: Nisum API
  description: Technical Exercise for Nisum
  version: 1.0.0
  name: Gustavo Alfredo Martínez
  email: gustavo-9189@hotmail.com

constants:
  authorization: Authorization
  bearer: Bearer
  secret: 343f7d35-005b-48a9-bb5e-5b25dbbd638a
  seconds: 2_592_000L


validation:
  password: ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$
