DROP SCHEMA IF EXISTS NISUM;

CREATE SCHEMA NISUM;

DROP TABLE IF EXISTS USER_APP;

CREATE TABLE USER_APP
(
    ID       UUID PRIMARY KEY,
    NAME     VARCHAR NOT NULL,
    EMAIL    VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    ISACTIVE BOOLEAN
);

INSERT INTO USER_APP
VALUES ('3051b858-2034-4db3-a397-e84d0e90ba1e',
        'Gustavo Martinez',
        'gustavo@gmail.com',
        '$2a$10$QGyxnUvHcJQGGyNisdqv/OhpxdvigB58S56kfVbzYhQl5z3tuc5wC',
        1);

DROP TABLE IF EXISTS PHONE;

CREATE TABLE PHONE
(
    ID           UUID PRIMARY KEY,
    ID_USER      UUID,
    NUMBER       VARCHAR(15) NOT NULL,
    CITY_CODE    VARCHAR(15) NOT NULL,
    COUNTRY_CODE VARCHAR(15) NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES USER_APP (ID)
);
